# Generated by Django 5.0 on 2023-12-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivar',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
