# Generated by Django 5.0 on 2023-12-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0002_alter_cultivar_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
