# Generated by Django 5.0 on 2023-12-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0003_rename_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tea',
            name='images',
        ),
    ]
