# Generated by Django 5.0 on 2023-12-17 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0005_image_tea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='teas',
        ),
        migrations.AddField(
            model_name='tea',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tea.profile'),
            preserve_default=False,
        ),
    ]
