# Generated by Django 5.0 on 2023-12-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0006_remove_profile_teas_tea_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='country',
            new_name='province',
        ),
    ]
