# Generated by Django 5.0 on 2023-12-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0008_tea_region_alter_tea_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='season',
            field=models.CharField(choices=[('W', 'Wiosna'), ('L', 'Lato'), ('J', 'Jesień'), ('Z', 'Zima')], max_length=1, null=True),
        ),
    ]
