# Generated by Django 4.2.8 on 2023-12-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0009_alter_tea_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='season',
            field=models.CharField(blank=True, choices=[('W', 'Wiosna'), ('L', 'Lato'), ('J', 'Jesien'), ('Z', 'Zima')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
