# Generated by Django 4.2.8 on 2023-12-22 16:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0010_alter_tea_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tea',
            name='brews',
        ),
        migrations.AddField(
            model_name='brew',
            name='tea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tea.tea'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tea',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
