# Generated by Django 4.2.8 on 2023-12-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0011_remove_tea_brews_brew_tea_alter_tea_date_finished_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
