# Generated by Django 4.2.8 on 2023-12-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0012_alter_country_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tea-images')),
                ('brew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.brew')),
            ],
        ),
    ]
