# Generated by Django 4.2.8 on 2023-12-22 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0015_alter_tea_country_alter_tea_cultivar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='last_viewed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tea',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
