# Generated by Django 4.2.8 on 2023-12-22 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0016_tea_last_viewed_alter_tea_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='last_viewed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 22, 17, 25, 29, 396851)),
        ),
    ]
