# Generated by Django 4.2.8 on 2024-02-10 23:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0020_alter_country_name_alter_cultivar_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='store',
            name='website',
            field=models.URLField(verbose_name='Strona internetowa'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='Dodatkowe uwagi'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tea.country', verbose_name='Kraj'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='cultivar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tea.cultivar', verbose_name='Kultywar'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='grams_left',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pozostało gramów'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='harvest_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zbiorów'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='price_per_100_grams',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cena za 100 gramów'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tea.province', verbose_name='Prowincja'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tea.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Ocena'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='season',
            field=models.CharField(blank=True, choices=[('W', 'Wiosna'), ('L', 'Lato'), ('J', 'Jesień'), ('Z', 'Zima')], max_length=1, verbose_name='Sezon'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tea.store', verbose_name='Sklep'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='store_description',
            field=models.TextField(blank=True, verbose_name='Opis sprzedawcy'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='tasting_notes',
            field=models.TextField(blank=True, verbose_name='Nuty smakowe'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tea.type', verbose_name='Typ herbaty'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='user_description',
            field=models.TextField(blank=True, verbose_name='Opis własny'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nazwa'),
        ),
    ]
