# Generated by Django 4.2.8 on 2024-02-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0021_alter_country_name_alter_cultivar_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='website',
            field=models.URLField(unique=True, verbose_name='Strona internetowa'),
        ),
    ]
