# Generated by Django 4.2.8 on 2024-02-20 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0023_alter_province_country_alter_region_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.profile', verbose_name='Profil'),
        ),
    ]
