# Generated by Django 4.2.8 on 2024-02-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0024_alter_tea_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nazwa'),
        ),
    ]
