# Generated by Django 4.2.8 on 2024-04-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0025_alter_profile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil'},
        ),
    ]
