# Generated by Django 4.2.11 on 2024-04-15 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0027_alter_brew_options_alter_brewimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='grams',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Gramy'),
        ),
        migrations.AddField(
            model_name='brew',
            name='water_ml',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ilość wody'),
        ),
    ]
