# Generated by Django 4.2.11 on 2024-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0029_alter_brew_tasting_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='Stosunek'),
        ),
    ]
