# Generated by Django 4.2.11 on 2024-04-19 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0030_brew_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='water_ml',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ilość wody (ml)'),
        ),
    ]
